name: Build and Push Strapi Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:  
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        region: ${{ secrets.AWS_REGION }}

    - name: Create ECR repository if not exists
      run: |
        aws ecr describe-repositories --repository-names strapi \
        || aws ecr create-repository --repository-name strapi

    - name: Build Docker image
      run: |
        IMAGE_TAG=latest-$(date +%s)
        echo "$IMAGE_TAG" > image_tag.txt
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/strapi:$IMAGE_TAG .

    - name: Push Docker image to ECR
      run: |
        IMAGE_TAG=$(cat image_tag.txt)
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/strapi:$IMAGE_TAG

    - name: Print Image Tag for Secrets
      run: |
        IMAGE_TAG=$(cat image_tag.txt)
        echo "Your image tag is: $IMAGE_TAG"
