name: Build and Push Strapi Docker Image to Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set image tag
      run: |
        IMAGE_TAG=latest-$(date +%s)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo $IMAGE_TAG > image_tag.txt

    - name: Log in to Docker Hub
      run: echo "${{ env.DOCKERHUB_PASSWORD }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t $DOCKERHUB_USERNAME/strapi:$IMAGE_TAG .

    - name: Push image to Docker Hub
      run: |
        docker push $DOCKERHUB_USERNAME/strapi:$IMAGE_TAG

    - name: Print Docker Image Tag
      run: echo "Docker Image Tag: $IMAGE_TAG"
