name: Deploy Strapi to EC2 using Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      IMAGE_TAG: ${{ secrets.IMAGE_TAG }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Read image tag from Secrets
      run: echo "IMAGE_TAG=${{ secrets.IMAGE_TAG }}" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Clean Terraform cache
      working-directory: ./terraform
      run: |
        rm -rf .terraform


    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: ./terraform
      run: |
           terraform plan \
            -var="image_tag=${IMAGE_TAG}" \
            -var="aws_region=${AWS_REGION}" \
            -var="aws_access_key_id=${AWS_ACCESS_KEY_ID}" \
            -var="aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" \
            -var="key_name=${KEY_NAME}" \
            -var="instance_type=t2.medium"
            
    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve \
           -var="image_tag=${IMAGE_TAG}" \
           -var="key_name=${{ secrets.KEY_NAME }}" \
           -var="instance_type=t2.medium" \
           -var="aws_region=${{ secrets.AWS_REGION }}" \
           -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
           -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
