name: Deploy Strapi to EC2 using Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Clean Terraform cache
      working-directory: ./terraform
      run: rm -rf .terraform

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Read IMAGE_TAG from file
      id: read_image_tag
      run: echo "IMAGE_TAG=$(cat image_tag.txt)" >> $GITHUB_ENV

    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan -var="image_tag=${IMAGE_TAG}" -var="dockerhub_username=${DOCKERHUB_USERNAME}" -var="key_name=${{ secrets.KEY_NAME }}" -var="subnet_id=${{ secrets.SUBNET_ID }}" -var="vpc_id=${{ secrets.VPC_ID }}"
      env:
          TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          TF_VAR_dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve -var="image_tag=${IMAGE_TAG}" -var="dockerhub_username=${DOCKERHUB_USERNAME}" -var="key_name=${{ secrets.KEY_NAME }}" -var="subnet_id=${{ secrets.SUBNET_ID }}" -var="vpc_id=${{ secrets.VPC_ID }}"
      env:
          TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          TF_VAR_dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
